### ISSUE TITLE
afc2d binary doesn't seem to be downloaded on iOS 14

### ISSUE THREAD

**Issue by PoomSmart** [Cannathea/afc2d-arm64#12] opened 2021-03-27 09:15 UTC
I observe that `killdaemon` isn't executed on AFC2 install. I had to execute it manually to get a valid afc2d binary. **This happens without any host blockers installed or weird hosts file modified.**

**Comment by JEmlay** [comment] 2021-03-29 16:07
Thanks for this!  I was scratching my head for a while because the USB-C port on my iPad is going bad.  I thought it completely died on me until I noticed iTunes was connecting.  Executing killdaemon got me working again.

So yeah, that last update goofed something up.  What's weird is while afcd isn't running (even though that package was installed) 3UTools refused to connect at all.  Even if it's jailed it still connects.  Removing AFC allowed it to connect again but jailed.  Installing AFC again made it not connect at all.  Now with the binary properly running it connects and I get root.

**Comment by zippoking** [comment] 2021-03-30 07:36
I have noticed the same thing on my iPad Air 2020 (4th Generation). As soon as i install the latest update of Apple File Conduit 2, i can´t get the connection to work with 3UTools or iFunbox. 

But i dont understand how you guys fixed it. What does it mean to manually execute killdaemon? Like in a Terminal? Can you give me the exact command i have to execute?

Thanks for you help.
Best regards
Zippoking

**Comment by PoomSmart** [comment] 2021-03-30 11:00
@zippoking You can use Filza, navigate to `/usr/bin` then execute `killdaemon` directly from there.

**Comment by zippoking** [comment] 2021-03-30 13:38
Wow. That was easy! Works like a charm. 

Thank you so much!

**Comment by JEmlay** [comment] 2021-04-14 17:09
Don't install v1.1.3!  I figured it was a fix for this and now it's completely hosed.

**Comment by hirakujira** [comment] 2021-04-14 17:38
We figured out the reason. v1.1.4 is on the way and will fix this.

**Comment by hirakujira** [comment] 2021-04-15 04:57
v1.1.4 is out and fixed this. If this still occurs, please reopen this issue.

**Closed as completed** 2021-04-15 04:57 UTC

**Comment by howardcg1126** [comment] 2022-04-11 09:20
I use the command killdaemon but nothing happens, what can I do?

**Comment by ichitaso** [comment] 2022-04-11 13:46
Can you access this URL?
http://appldnld.apple.com
If it is blocked in the hosts file or other files, it will not work.
Also, if SpringBoard has the "/usr/libexec/afc2dSupport" file when it is restarted after installation, it will be enabled if the above is not a problem.

**Comment by howardcg1126** [comment] 2022-04-13 08:09
If it is blocked in the hosts file or other files, What should I do to fix?
Also, killdaemon can't even execute the install.

**Comment by ichitaso** [comment] 2022-04-13 19:32
Open /private/etc/hosts with Filza File Manager or WinSCP (OpenSSH required), etc. If you find the string "appldnld.apple.com" and it matches, delete that part.

EDIT: v1.1.6 Fixed this Issue
https://github.com/Cannathea/afc2d-arm64/commit/b7e036a19dcd996a90ff6c23b15d9bef2cef221f

If the problem is caused by other ad-blocking applications or packages, please take care of it there.
